#To use this make file, navigate to the directory containing the makefile and type "make"
#		

all: fibrec fibit counter_rec

fibrec: fibrec.c
	gcc -std=c11 -o fibrec.exe fibrec.c
	
fibit: fibit.c
	gcc -std=c11 -o fibit.exe fibit.c
	

	
counter_rec: counter_rec.c
	gcc -std=c11 -o counter.exe counter_rec.c
